### ISSUE TITLE
Abstürze, RedMatic-HomeKit lässt sich nicht installieren

### ISSUE THREAD

**Issue by superpower10** [rdmtc/RedMatic-HomeKit#146]
Hier das Log:

```
May  9 17:30:06 ccu3-webui daemon.err node-red: 9 May 17:30:06 - [red] Uncaught Exception:
May  9 17:30:06 ccu3-webui daemon.err node-red: 9 May 17:30:06 - Error: This callback function has already been called by someone else; it can only be called one time.
May  9 17:30:06 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/util/once.js:12:13
May  9 17:30:06 ccu3-webui daemon.err node-red:     at Characteristic.LeakDetected.addListener.callback (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/homematic-devices/lib/accessory.js:203:13)
May  9 17:30:06 ccu3-webui daemon.err node-red:     at Characteristic.LeakDetected.emit (events.js:194:15)
May  9 17:30:06 ccu3-webui daemon.err node-red:     at Characteristic.LeakDetected.Characteristic.getValue (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
May  9 17:30:06 ccu3-webui daemon.err node-red:     at Bridge.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Accessory.js:769:20)
May  9 17:30:06 ccu3-webui daemon.err node-red:     at Array.forEach (<anonymous>)
May  9 17:30:06 ccu3-webui daemon.err node-red:     at Bridge.Accessory._handleGetCharacteristics (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Accessory.js:733:8)
May  9 17:30:06 ccu3-webui daemon.err node-red:     at HAPServer.emit (events.js:189:13)
May  9 17:30:06 ccu3-webui daemon.err node-red:     at HAPServer._handleCharacteristics (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/HAPServer.js:926:10)
May  9 17:30:06 ccu3-webui daemon.err node-red:     at HAPServer.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
May  9 17:30:06 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 1
```

**Comment by hobbyquaker** [comment]
habe eine vermutung, ich befürchte da gibts ein schwerwiegenden bug beim bereitstellen von heizungsgruppen in homekit. Falls Du die verwendest: starte mal im Safe Mode und deaktiviere im CCU Configuration Node das VirtualDevices Interface.

**Comment by hobbyquaker** [comment]
Oh, ah halt. Bei Dir hat es wohl eine andere Ursache, da gehts um ein Wassermelder. Muss ich untersuchen.

**Comment by hobbyquaker** [comment]
Was mir sehr helfen würde wär mal ein Log auf Debug Level dass alles vom Start bis zum Crash enthält.

**Comment by superpower10** [comment]
OK. Habe auf Debug gestellt.

Sobald es wieder abstürzt, werde ich das LOG-File hier posten

**Comment by superpower10** [comment]
Also nachdem ich mehrere Updates gemacht habe. Raspberrymatic und Redmatic auf die neueste Version, startet Redmatic gar nicht mehr.

```
May 12 14:50:19 ccu3-webui daemon.info node-red[790]: Starting flows
May 12 14:50:19 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] local connection on ccu >= v3.41 detected
May 12 14:50:20 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] paramsets loaded from /usr/local/addons/redmatic/var/paramsets.json
May 12 14:50:20 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] metadata loaded from /usr/local/addons/redmatic/var/ccu_localhost.json
May 12 14:50:20 ccu3-webui daemon.info node-red[790]: Started flows
May 12 14:50:21 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] Interfaces: ReGaHSS, BidCos-RF, HmIP-RF, VirtualDevices
May 12 14:50:21 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] ReGaHSS binrpc port 31999 connected
May 12 14:50:21 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] init BidCos-RF binrpc://127.0.0.1:2047 nr_AKHydZ_BidCos-RF
May 12 14:50:21 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] init HmIP-RF http://127.0.0.1:2048 nr_D24DjW_HmIP-RF
May 12 14:50:21 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] init VirtualDevices http://127.0.0.1:2048 nr_D24DjW_VirtualDevices
May 12 14:50:21 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] binrpc server listening on binrpc://127.0.0.1:2047
May 12 14:50:21 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] xmlrpc server listening on http://127.0.0.1:2048
May 12 14:50:22 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] HmIP-RF http port 32010 connected
May 12 14:50:22 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] BidCos-RF binrpc port 32001 connected
May 12 14:50:23 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] metadata saved to /usr/local/addons/redmatic/var/ccu_localhost.json
May 12 14:50:23 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] metadata saved to /usr/local/addons/redmatic/var/ccu_localhost.json
May 12 14:50:31 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] VirtualDevices http port 39292 connected
May 12 14:50:31 ccu3-webui daemon.info node-red[790]: [redmatic-homekit-homematic-devices:d2eec606.c68ba] publish 47 devices
May 12 14:50:51 ccu3-webui daemon.info node-red[790]: [redmatic-homekit-homematic-devices:d2eec606.c68ba] publish done
May 12 14:50:55 ccu3-webui daemon.info node-red[790]: [redmatic-homekit-bridge:RedMatic Bridge] bridge already published (46 Accessories) RedMatic Bridge CC:22:3D:FB:81:EC on port 51826
May 12 14:54:57 ccu3-webui daemon.info redmatic: Stopping Node-RED
May 12 14:54:57 ccu3-webui daemon.info node-red[790]: Stopping flows
May 12 14:54:58 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] de-init BidCos-RF binrpc://127.0.0.1:2047 done
May 12 14:54:58 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] de-init HmIP-RF http://127.0.0.1:2048 done
May 12 14:54:58 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] de-init VirtualDevices http://127.0.0.1:2048 done
May 12 14:54:58 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] binrpc server closed
May 12 14:54:58 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] xmlrpc server closed
May 12 14:54:58 ccu3-webui daemon.info node-red[790]: [ccu-connection:localhost] rpc close done
May 12 14:54:58 ccu3-webui daemon.info node-red[790]: Stopped flows
May 12 14:54:59 ccu3-webui daemon.info redmatic: Node-RED stopped
May 12 15:07:48 ccu3-webui daemon.info redmatic-pkg: Package redmatic-homekit update 2.3.2 to 2.3.3
May 12 15:07:48 ccu3-webui daemon.info redmatic-pkg: Get https://github.com/rdmtc/RedMatic/releases/download/v4.4.3/redmatic-pkg-redmatic-homekit-2.3.3.tar.gz
May 12 15:47:43 ccu3-webui daemon.info redmatic-pkg: Package redmatic-homekit update 2.3.2 to 2.3.3
May 12 15:47:43 ccu3-webui daemon.info redmatic-pkg: Get https://github.com/rdmtc/RedMatic/releases/download/v4.4.3/redmatic-pkg-redmatic-homekit-2.3.3.tar.gz
May 12 16:03:32 ccu3-webui daemon.info redmatic-pkg: Package redmatic-homekit update 2.3.2 to 2.3.3
May 12 16:03:32 ccu3-webui daemon.info redmatic-pkg: Get https://github.com/rdmtc/RedMatic/releases/download/v4.4.3/redmatic-pkg-redmatic-homekit-2.3.3.tar.gz
```

**Comment by hobbyquaker** [comment]
Args, blödes Problem: Beim ersten Start nach einem Update versucht das Startscript die Zusatzpakete mit Binärabhängigkeiten (also alle die im RedMatic UI unter "Packages" installiert sind) zu aktualiseren. Dazu versucht es die redmatic-pkg-*.tar.gz Dateien direkt von Github runterzuladen (ersichtlich in Deinem Log ganz unten: `Get https://github.com/rdmtc/RedMatic/releases/download/v4.4.3/redmatic-pkg-redmatic-homekit-2.3.3.tar.gz`). Das scheint nie zu einem Ende zu kommen, ich vermute/befürchte dass Du grade auch auf ein Problem stößt dass zur Zeit um sich greift: superlangsame Github Downloads, sowohl bei der Telekom als auch bei Unity seit einigen Wochen immer wieder nur ein paar KB/s... Das RedMatic-HomeKit Paket dass er da laden will ist 22MB groß...

Als schnellen Workaround würde ich folgendes Vorschlagen:
Die Datei `/usr/local/addons/redmatic/var/do_pkg_upgrade` löschen und dann nochmal RedMatic neu starten. Dann versucht er nicht die Updates zu ziehen. Später kannst dann das Update von RedMatic-HomeKit nochmal manuell versuchen indem Du es einfach im RedMatic UI unter Packages einmal deinstallierst und dann wieder neu installierst, anschließend Node-RED neu starten.

**Comment by superpower10** [comment]
So etwas ähnliches hatte ich mir schon gedacht und bereits HomeKit deinstalliert. Danach hat sich Redmatic automatisch gestartet.

Jetzt versuche ich gerade HomeKit wieder zu installieren.

Danach gebe ich Bescheid.

**Comment by superpower10** [comment]
In /usr/local/addons/redmatic/var/pkg-upgrade.log steht:
```
Package redmatic-homekit update 2.3.2 to 2.3.3
Get https://github.com/rdmtc/RedMatic/releases/download/v4.4.3/redmatic-pkg-redmatic-homekit-2.3.3.tar.gz
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
```

**Comment by hobbyquaker** [comment]
Hmm. Macht mich erstmal ratlos. Gibt es bei Dir spezielle Netzwerkbegenheiten (Firewall, Proxy, ...) oder hängt die CCU "ganz normal" über einen Consumer-Router (Fritzbox, Speedport, ...) am Internet? Aus irgendeinem Grund scheitert da wohl die TLS Negotation zwischen Curl und dem Github bzw. Amazon S3 Webserver. Wenn Du ein "ganz normales" Netzwerk hast würde ich vorschlagen (ein bisschen aus Verzweiflung weil mir nichts besseres einfällt, aber schaden tut es sicher nicht) mal alles neuzustarten (Router, CCU) und es einfach noch mal zu probieren.

**Comment by superpower10** [comment]
Kein Chance. RedMatic-HomeKit lässt sich nicht installieren. Es dreht und dreht und nichts passiert. Auch nach Stunden nicht. 
Kann man das auch selbst herunterladen und installieren? Wenn ja, wie?

**Comment by hobbyquaker** [comment]
Manuell auf der Commandline sollte der Download via Curl und die Installation so funktionieren:

```
/usr/bin/curl https://github.com/rdmtc/RedMatic/releases/download/v4.6.0/redmatic-pkg-redmatic-homekit-2.3.3.tar.gz -o /usr/local/addons/redmatic/tmp/redmatic-homekit.tar.gz --location

cd /usr/local/addons/redmatic

tar --no-same-owner -xzf tmp/redmatic-homekit.tar.gz

rm tmp/redmatic-homekit.tar.gz

/etc/config/rc.d/redmatic restart
```

Wenn das mit dem Curl schon fehlschlägt könntest die Datei auch anderswo runterladen und per (win)scp nach /usr/local/addons/redmatic/tmp/redmatic-homekit.tar.gz kopieren.

**Comment by superpower10** [comment]
Also es liegt wohl doch an GitHub. Die Geschwindigkeit ist unter aller s....

<img width="617" alt="Bildschirmfoto 2019-05-14 um 20 53 56" src="https://user-images.githubusercontent.com/20533966/57724181-7b6fce00-768a-11e9-8543-c3fc8de1903c.png">

Deswg. fände ich es gut, wenn man so eine Anzeige auch auf der GUI im Web sehen würde, dann wüsste man Bescheid...

Aber auch die CCU3 ist seit der neuesten RaspberryMatic Version unglaublich langsam beim installieren von Add-Ons und Backups wieder einspielen (Security lässt wohl grüßen)

**Comment by superpower10** [comment]
So jetzt hat es funktioniert. Vielen Dank
