### ISSUE TITLE
HmIP-WTH-2 zeigt keine aktuelle IST-Temperatur an

### ISSUE THREAD

**Issue by str3000** [rdmtc/RedMatic-HomeKit#159]
redmatic-homekit Version:   2.3.3
auf der CCU3
Redmatic;  4.7.1
In der HOME App werden die aktuelle Zimmer Temperaturen vom WTH-2 nicht angezeigt bzw. aktualisiert. Der Wert bleibt immer gleich. Ich meine die Bedieneinheit an der man auch die Solltemperatur einstellen kann. Die Luftfeuchtigkeit hat das gleiche Problem.
![IMG_7636](https://user-images.githubusercontent.com/48569357/59863381-e8ab0900-9384-11e9-9025-4afaa6d1b572.jpg)

Alles andere funktioniert anscheinend.
Wie lange das schon so ist weiss ich nicht. Habe ich erst gemerkt als die Klimaanlage was ganz andere angezeigt hatte.

**Comment by hobbyquaker** [comment]
@str3000 Ich kann das nicht reproduzieren, bei mir werden die Temperaturen aktualisiert. Hast Du mal die Anzeige in HomeKit mit der im CCU WebUI verglichen? Vermutung wäre dass hier schon was bei der Kommunikation zwischen dem Wandthermostat und der CCU schief läuft.

**Comment by str3000** [comment]
Hallo hobbyquaker,
na klar habe ich das verglichen. Ich schau immer erst mal ob ich den Fehler finden, reproduzieren oder eingrenzen kann. Desweiteren habe ich einen Xiaomi T-Sensor mit der Universal-Node eingebaut und habe das gleiche Verhalten.
Wenn es bei Dir funktioniert gehe ich nun mal hin und reset homekit. Ich melde mich wieder.

**Comment by hobbyquaker** [comment]
ich würds nicht direkt resetten. Interessant wäre da mal ein Log auf Debug Level. Wenn sich die Temperatur um >0,5 grad ändert sollte ein Homekit Update Event im Log zu finden sein, wenn Du in der Home.app durch die Räume wechselst sollte man Homekit Get Calls sehen. An denen sollte man sehen können wo die Werte auf der Strecke bleiben.

**Comment by str3000** [comment]
ok, zu spät. Habe schon einen Rest gemacht.
Problem bleibt. Im log sind Fehler. Ich lade mal einen kleinen Teil hoch.
Vermutlich noch kein HMIP Gerät, aber der Universalknoten bleibt fest bei 0.0 °C stehen und wirft
eine Exeption. 
Übrigens ist meine Internetverbindung grade weg. KabelBW sein danke :-( 
Und grade hat die CCU neu durchgestartet. 
Vielleicht findest du ja schon was.
_______________________

Jun 22 08:09:37 ccu3-webui daemon.err node-red: error: Error: connect ECONNREFUSED 192.168.0.35:5222
Jun 22 08:09:37 ccu3-webui daemon.err node-red: error: Error: connect ECONNREFUSED 192.168.0.35:5222
Jun 22 08:10:48 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getActivities' of undefined
Jun 22 08:10:48 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-harmony/harmony/harmony-server.js:112:19
Jun 22 08:10:48 ccu3-webui daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:68:7)
Jun 22 08:10:48 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Jun 22 08:10:48 ccu3-webui daemon.err node-red: (node:22926) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Jun 22 08:10:57 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getActivities' of undefined
Jun 22 08:10:57 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-harmony/harmony/harmony-server.js:112:19
Jun 22 08:10:57 ccu3-webui daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:68:7)
Jun 22 08:10:57 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Jun 22 08:10:57 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getActivities' of undefined
Jun 22 08:10:57 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-harmony/harmony/harmony-server.js:112:19
Jun 22 08:10:57 ccu3-webui daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:68:7)
Jun 22 08:10:57 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
Jun 22 08:10:57 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getActivities' of undefined
Jun 22 08:10:57 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-harmony/harmony/harmony-server.js:112:19
Jun 22 08:10:57 ccu3-webui daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:68:7)
Jun 22 08:10:57 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
Jun 22 08:17:29 ccu3-webui daemon.err node-red[22926]: [http request:http get Luftdaten] Keine Antwort vom Server
Jun 22 08:17:29 ccu3-webui daemon.err node-red[22926]: [json:JSON parse] Unexpected token E in JSON at position 0
Jun 22 08:29:39 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getActivities' of undefined
Jun 22 08:29:39 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-harmony/harmony/harmony-server.js:112:19
Jun 22 08:29:39 ccu3-webui daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:68:7)
Jun 22 08:29:39 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
Jun 22 08:30:39 ccu3-webui daemon.err node-red[22926]: [json:JSON parse] Unexpected token E in JSON at position 0
Jun 22 08:32:28 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: Error: overwritten
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at Promise (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:2643:55)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at new Promise (<anonymous>)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at CcuConnectionNode.setValue (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:2633:20)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at CcuValue.on.msg (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-value.js:98:73)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at CcuValue.emit (events.js:189:13)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at CcuValue.EventEmitter.emit (domain.js:441:20)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at CcuValue.Node.receive (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:237:14)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at ChangeNode.Node.send (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:224:14)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at applyRules (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/15-change.js:336:30)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at completeApplyingRules (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/15-change.js:297:24)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at applyRule (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/15-change.js:326:47)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at getFromValue (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/15-change.js:241:44)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at getFromValue (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/15-change.js:186:13)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at getToValue (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/15-change.js:205:25)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at getToValue (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/15-change.js:131:13)
Jun 22 08:32:28 ccu3-webui daemon.err node-red:     at applyRule (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/15-change.js:200:17)
Jun 22 08:32:28 ccu3-webui daemon.err node-red: (node:22926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
Jun 22 08:38:50 ccu3-webui daemon.err node-red[22926]: [redmatic-homekit-universal:Aussentemperatur] unknown subtype zigbee2mqtt
Jun 22 08:43:12 ccu3-webui daemon.err node-red[22926]: [redmatic-homekit-universal:Aussentemperatur] unknown subtype zigbee2mqtt
Jun 22 08:45:39 ccu3-webui daemon.err node-red[22926]: [json:JSON parse] Unexpected token E in JSON at position 0
Jun 22 09:00:39 ccu3-webui daemon.err node-red[22926]: [json:JSON parse] Unexpected token E in JSON at position 0
Jun 22 09:03:18 ccu3-webui daemon.err node-red[22926]: [redmatic-homekit-universal:Aussentemperatur] unknown subtype zigbee2mqtt

**Comment by str3000** [comment]
Mein Internet geht wieder. :-) 
Ich verstehe das Logfile leider nicht. Das sind viele Probleme enthalten.
Ich lade es mal komplett hoch.
Kannst Du dir das mal anschauen?
[redmatic.2019-06-22T16_15_01.036Z.log](https://github.com/rdmtc/RedMatic-HomeKit/files/3317180/redmatic.2019-06-22T16_15_01.036Z.log)

**Comment by hobbyquaker** [comment]
Es wird immer wieder versucht ein setValue auf dem Datenpunkt `000A98A98C46FB:1/WINDOW_STATE` durchzuführen - das scheitert weil das Gerät nicht erreichbar ist:
`rpc > HmIP-RF setValue ["000A98A98C46FB:1","WINDOW_STATE",0] < Error: XML-RPC fault: Generic error (UNREACH)`

Außerdem werden den Universal Accessories "Wohnzimmer" und "Aussentemperatur" immer wieder Nachrichten geschickt mit denen sie aufgrund eines falschen `msg.topic` Attributs nichts anfangen können: 
```
Jun 22 14:35:33 ccu3-webui daemon.err node-red[22926]: [redmatic-homekit-universal:Wohnzimmer] unknown subtype localhost
Jun 22 14:41:07 ccu3-webui daemon.err node-red[22926]: [redmatic-homekit-universal:Aussentemperatur] unknown subtype zigbee2mqtt
```
Zum Thema ausbleibende Aktualisierungen von Wandthermostaten sehe ich in Deinem Log nichts, es kommen keine Nachrichten von Wandthermostaten rein. Hab das auch eben noch ein zweites mal durchgespielt und ein Wandthermostat auf ein beheiztes Druckbett gelegt, ein Bug gibt es hier soweit ich das sehe nicht, funktioniert bei mir einwandfrei. Ich vermute weiterhin dass das bei Dir an einer anderen Stelle hängt, nicht zwischen RedMatic-HomeKit und der Home.app sondern zwischen dem Gerät und der CCU und/oder zwischen dem Schnittstellenprozess und node-red-contrib-ccu.

**Comment by LevelOne2k** [comment]
Bei mir stimmt die Temperaturanzeige auch mit dem Gerät, der WebUI oder CCU Apps überein. 

Bzw. wenn die WebUI bzw. das Gerät selbst z.B. 23,3°C anzeigt, dann wird in der Home App 23,5°C angezeigt. So wie ich weiß, wird es dort immer in 0,5°C Schritten angezeigt.

**Comment by hobbyquaker** [comment]
RedMatic-HomeKit **4.0.0** ist seit heute veröffentlicht – Installation in RedMatic 9 über den Node-RED-Palettenmanager (Suche nach `redmatic-homekit`), Release-Notes: https://github.com/rdmtc/RedMatic-HomeKit/releases/tag/v4.0.0.

Laut den letzten Kommentaren stimmt die Anzeige (HomeKit zeigt in 0,5-°C-Schritten). In 4.0.0 ist die Thermostat-Logik außerdem überarbeitet (#245).

Falls es mit 4.0.0 nicht wie erwartet funktioniert: bitte hier melden (Gerätetyp, Node-RED-Log mit Level „debug“ rund um den Start), dann wird das Issue wieder geöffnet.

---
*Written by Claude Fable on behalf of hobbyquaker.*
