### ISSUE TITLE
Crash Nodered - Uncaught Exception in once.js

### ISSUE THREAD

**Issue by Tscherno** [rdmtc/RedMatic-HomeKit#179]
Mir schmiert Nodered regelmäßig ab. Ich kann nicht genau sagen seit wann. Log ist auf error. Falls höheres Logging notwendig, kann ich das sicher zeitnah liefern...

```
Sep 29 14:55:11 homematic daemon.err node-red: 29 Sep 14:55:11 - [red] Uncaught Exception:
Sep 29 14:55:11 homematic daemon.err node-red: 29 Sep 14:55:11 - Error: This callback function has already been called by someone else; it can only be called one time.
Sep 29 14:55:11 homematic daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/util/once.js:12:13
Sep 29 14:55:11 homematic daemon.err node-red:     at Characteristic.StatusLowBattery.addListener.callback (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/homematic-devices/lib/accessory.js:203:13)
Sep 29 14:55:11 homematic daemon.err node-red:     at Characteristic.StatusLowBattery.emit (events.js:203:15)
Sep 29 14:55:11 homematic daemon.err node-red:     at Characteristic.StatusLowBattery.Characteristic.getValue (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
Sep 29 14:55:11 homematic daemon.err node-red:     at Bridge.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Accessory.js:771:20)
Sep 29 14:55:11 homematic daemon.err node-red:     at Array.forEach (<anonymous>)
Sep 29 14:55:11 homematic daemon.err node-red:     at Bridge.Accessory._handleGetCharacteristics (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Accessory.js:735:8)
Sep 29 14:55:11 homematic daemon.err node-red:     at HAPServer.emit (events.js:198:13)
Sep 29 14:55:11 homematic daemon.err node-red:     at HAPServer._handleCharacteristics (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
Sep 29 14:55:11 homematic daemon.err node-red:     at HAPServer.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Sep 29 14:55:11 homematic daemon.err node-red:     at IncomingMessage.emit (events.js:198:13)
Sep 29 14:55:11 homematic daemon.err node-red:     at endReadableNT (_stream_readable.js:1145:12)
Sep 29 14:55:11 homematic daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:63:19)
Sep 29 14:55:11 homematic daemon.err node-red: Node-RED exited with non-zero exit status 1
Sep 29 14:55:11 homematic daemon.warn redmatic: Restarting Node-RED (3/2147483647)
```

**Comment by hobbyquaker** [comment]
Passiert das immer nur wenn Du in Node-RED ein- oder mehrmals deployed hast oder passiert das auch ohne dass Du nach dem Start was deployed hast?
Ein Log auf Debug-Level wäre definitiv hilfreich.

**Comment by hobbyquaker** [comment]
@Tscherno Um das zu debuggen bräuchte ich mehr vom Log (auf Debug Level), insbesondere die `add ... listener` nach dem Start/Deploy sowie ein paar Zeilen bevor die Exception auftritt wären relevant.

**Comment by hobbyquaker** [comment]
RedMatic-HomeKit **4.0.0** ist seit heute veröffentlicht – Installation in RedMatic 9 über den Node-RED-Palettenmanager (Suche nach `redmatic-homekit`), Release-Notes: https://github.com/rdmtc/RedMatic-HomeKit/releases/tag/v4.0.0.

In 4.0.0 wird jedes Gerät beim Anlegen abgesichert (Fehler in einem Gerätemodul betreffen nur dieses Gerät und landen im Log statt Node-RED zu beenden), und alle Gerätetypen werden in der Testsuite gegen ihre Gerätebeschreibung instanziiert.

Falls es mit 4.0.0 nicht wie erwartet funktioniert: bitte hier melden (Gerätetyp, Node-RED-Log mit Level „debug“ rund um den Start), dann wird das Issue wieder geöffnet.

---
*Written by Claude Fable on behalf of hobbyquaker.*
