### ISSUE TITLE
Uncaught Exception: Steuerung ZigBee-Devices über HomeKit

### ISSUE THREAD

**Issue by cschneider1984** [rdmtc/RedMatic-HomeKit#270]
RedMatic Version: 5.5.3, node-red-contrib-zigbee Version: 0.18.2, redmatic-homekit, Version: 3.2.0

Ich verwende mehrere Hue-LightStrips (Philips LST002), die über node-red-contrib-zigbee angesprochen werden. Über die RedMatic HomeKit ZigBee-Node werden die ZigBee-Geräte in HomeKit bereitgestellt. Das Ein-/Ausschalten via HomeKit funktioniert einwandfrei. Sobald ich in der Apple Home-App aber eine Farbvorwahl vornehme, stürzt NodeRed reproduzierbar mit einer Uncaught Exception ab. Auszug aus dem Log:

```
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red: 30 Apr 20:35:55 - [red] Uncaught Exception:
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red: 30 Apr 20:35:55 - TypeError: Cannot read property 'attributes' of undefined
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at service.addService.get.set.get.set.get.set.setProps.get.set.get.set.data (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/zigbee-devices/zll.extendedcolor.js:53:93)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at Characteristic.Saturation.acc.addListener (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/zigbee-devices/lib/accessory.js:57:38)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at Characteristic.Saturation.emit (events.js:198:13)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at Characteristic.Saturation.Characteristic.setValue (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at Bridge.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Accessory.js:882:22)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at Array.forEach (<anonymous>)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at Bridge.Accessory._handleSetCharacteristics (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Accessory.js:822:8)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at HAPServer.emit (events.js:198:13)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at HAPServer._handleCharacteristics (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at HAPServer.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at IncomingMessage.emit (events.js:198:13)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at endReadableNT (_stream_readable.js:1145:12)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:63:19)
Apr 30 20:35:55 homematic-ccu2 daemon.err node-red: Node-RED exited with non-zero exit status 1
```
Vielen Dank vorab für alle Hinweise zur Problemlösung.

**Comment by fonnoir** [comment]
:(

**Comment by hobbyquaker** [comment]
Mit RedMatic-HomeKit 4.0.0 (in Entwicklung, aktuell `4.0.0-dev.6` auf master) entfällt der Zigbee-Node (ROADMAP.md, Entscheidung D-6): node-red-contrib-zigbee wird seit 2022 nicht mehr gepflegt und braucht native Module, die sich auf einer CCU nicht installieren lassen – RedMatic 9 unterstützt keine Binärabhängigkeiten mehr. Empfohlener Weg für Zigbee-Geräte in HomeKit: zigbee2mqtt plus der Universal-Node. Ich schließe das Issue daher.

_Geschrieben von Claude im Auftrag des Maintainers._
