### ISSUE TITLE
Uncaught Exception Garage Accessory

### ISSUE THREAD

**Issue by hobbyquaker** [rdmtc/RedMatic-HomeKit#286]
```
Jul  9 15:59:13 homematic-raspi daemon.err node-red: 9 Jul 15:59:13 - [red] Uncaught Exception:
Jul  9 15:59:13 homematic-raspi daemon.err node-red: 9 Jul 15:59:13 - TypeError: Cannot read property 'PARAMSETS' of undefined
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at CcuConnectionNode.paramsetQueuePush (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:1753:24)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at CcuConnectionNode.getParamsetDescription (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:1842:18)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at move (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/nodes/redmatic-homekit-homematic-garage.js:39:37)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at Characteristic.TargetDoorState.setTargetDoorStateListener (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/nodes/redmatic-homekit-homematic-garage.js:319:17)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at Characteristic.TargetDoorState.emit (events.js:198:13)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at Characteristic.TargetDoorState.Characteristic.setValue (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at Bridge.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Accessory.js:882:22)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at Array.forEach (<anonymous>)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at Bridge.Accessory._handleSetCharacteristics (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Accessory.js:822:8)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at HAPServer.emit (events.js:198:13)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at HAPServer._handleCharacteristics (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at HAPServer.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at IncomingMessage.emit (events.js:198:13)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at endReadableNT (_stream_readable.js:1145:12)
Jul  9 15:59:13 homematic-raspi daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:63:19)
Jul  9 15:59:13 homematic-raspi daemon.err node-red: Node-RED exited with non-zero exit status 1
```

**Comment by hobbyquaker** [comment]
RedMatic-HomeKit **4.0.0** ist seit heute veröffentlicht – Installation in RedMatic 9 über den Node-RED-Palettenmanager (Suche nach `redmatic-homekit`), Release-Notes: https://github.com/rdmtc/RedMatic-HomeKit/releases/tag/v4.0.0.

In 4.0.0 wird jedes Gerät beim Anlegen abgesichert (siehe #179); die Garage-Node-Ausnahme aus 3.x konnten wir nicht mehr reproduzieren.

Falls es mit 4.0.0 nicht wie erwartet funktioniert: bitte hier melden (Gerätetyp, Node-RED-Log mit Level „debug“ rund um den Start), dann wird das Issue wieder geöffnet.

---
*Written by Claude Fable on behalf of hobbyquaker.*
