### ISSUE TITLE
RedMatic stürzt wegen "node-red-contrib-lgtv" immer ab.

### ISSUE THREAD

**Issue by HookHM** [rdmtc/RedMatic-HomeKit#338]
Hallo,

ich hatte die Erweiterung "node-red-contrib-lgtv" immer installiert. Heute habe ich die neuste RaspberryMatic version neu aufgespielt bzw. komplett neu geflasht und ein CCU Backup eingespielt und dann die aktuelle RedMatic Version wieder installiert und dann die Pakete die ich installiert hatte, alles wunderbar, nur wenn ich "node-red-contrib-lgtv" wieder installiere, stürzt RedMatic immer ab. Wenn ich das Paket versuche in Node-Red unter "Palette Verwalten" installiere, schlägt das fehl und der unten gepostete Log erscheint. Was kann da los sein?

2021-11-14T16:49:48.520Z installieren : node-red-contrib-lgtv 1.1.0

2021-11-14T16:49:48.674Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-lgtv@1.1.0
2021-11-14T16:50:02.229Z [err] npm
2021-11-14T16:50:02.231Z [err]  
2021-11-14T16:50:02.232Z [err] ERR!
2021-11-14T16:50:02.233Z [err]  
2021-11-14T16:50:02.234Z [err] code
2021-11-14T16:50:02.235Z [err]  1
2021-11-14T16:50:02.236Z [err] npm
2021-11-14T16:50:02.237Z [err]  
2021-11-14T16:50:02.243Z [err] ERR! path
2021-11-14T16:50:02.244Z [err]  /usr/local/addons/redmatic/var/node_modules/node-red-contrib-lgtv/node_modules/utf-8-validate
2021-11-14T16:50:02.255Z [err] npm ERR! command failed
2021-11-14T16:50:02.255Z [err] npm ERR! command sh -c node-gyp-build
2021-11-14T16:50:02.255Z [err] npm ERR!
2021-11-14T16:50:02.256Z [err]  gyp info it worked if it ends with ok
2021-11-14T16:50:02.256Z [err] npm ERR! gyp info using node-gyp@7.1.2
2021-11-14T16:50:02.256Z [err] npm ERR!
2021-11-14T16:50:02.256Z [err]  gyp info using node@14.16.0 | linux | arm
2021-11-14T16:50:02.256Z [err] npm ERR! gyp ERR! find Python 
2021-11-14T16:50:02.256Z [err] npm ERR!
2021-11-14T16:50:02.257Z [err]  gyp ERR! find Python Python is not set from command line or npm configuration
2021-11-14T16:50:02.257Z [err] npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2021-11-14T16:50:02.257Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2021-11-14T16:50:02.257Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2021-11-14T16:50:02.257Z [err] npm 
2021-11-14T16:50:02.258Z [err] ERR! gyp ERR! find Python checking if "python" can be used
2021-11-14T16:50:02.258Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2021-11-14T16:50:02.258Z [err] npm ERR! gyp ERR! find Python checking if "python2" can be used
2021-11-14T16:50:02.258Z [err] npm 
2021-11-14T16:50:02.258Z [err] ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error
2021-11-14T16:50:02.258Z [err] npm ERR! gyp ERR! find Python 
2021-11-14T16:50:02.258Z [err] npm ERR!
2021-11-14T16:50:02.258Z [err]  gyp ERR! find Python **********************************************************
2021-11-14T16:50:02.258Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2021-11-14T16:50:02.258Z [err] npm
2021-11-14T16:50:02.259Z [err]  ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2021-11-14T16:50:02.259Z [err] npm ERR!
2021-11-14T16:50:02.259Z [err]  gyp ERR! find Python you can try one of the following options:
2021-11-14T16:50:02.259Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2021-11-14T16:50:02.259Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2021-11-14T16:50:02.259Z [err] npm 
2021-11-14T16:50:02.260Z [err] ERR! gyp ERR! find Python - Set the environment variable PYTHON
2021-11-14T16:50:02.260Z [err] npm ERR!
2021-11-14T16:50:02.260Z [err]  gyp ERR! find Python - Set the npm configuration variable python:
2021-11-14T16:50:02.260Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2021-11-14T16:50:02.260Z [err] npm
2021-11-14T16:50:02.260Z [err]  ERR! gyp ERR! find Python For more information consult the documentation at:
2021-11-14T16:50:02.260Z [err] npm ERR!
2021-11-14T16:50:02.260Z [err]  gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2021-11-14T16:50:02.260Z [err] npm ERR! gyp ERR! find Python **********************************************************
2021-11-14T16:50:02.261Z [err] npm ERR! gyp ERR! find Python 
2021-11-14T16:50:02.261Z [err] npm 
2021-11-14T16:50:02.261Z [err] ERR! gyp ERR! configure error 
2021-11-14T16:50:02.261Z [err] npm ERR!
2021-11-14T16:50:02.261Z [err]  gyp ERR! stack Error: Could not find any Python installation to use
2021-11-14T16:50:02.261Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:302:47)
2021-11-14T16:50:02.261Z [err] npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2021-11-14T16:50:02.261Z [err] npm ERR!
2021-11-14T16:50:02.262Z [err]  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2021-11-14T16:50:02.262Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:266:16)
2021-11-14T16:50:02.262Z [err] npm ERR! gyp ERR! stack     at exithandler (child_process.js:315:5)
2021-11-14T16:50:02.262Z [err] npm 
2021-11-14T16:50:02.262Z [err] ERR! gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
2021-11-14T16:50:02.262Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2021-11-14T16:50:02.263Z [err] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2021-11-14T16:50:02.263Z [err] npm 
2021-11-14T16:50:02.263Z [err] ERR! gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
2021-11-14T16:50:02.263Z [err] npm ERR!
2021-11-14T16:50:02.263Z [err]  gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-11-14T16:50:02.263Z [err] npm ERR! gyp ERR! System Linux 5.10.17
2021-11-14T16:50:02.263Z [err] npm ERR! gyp ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-11-14T16:50:02.263Z [err] npm 
2021-11-14T16:50:02.264Z [err] ERR! gyp ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-lgtv/node_modules/utf-8-validate
2021-11-14T16:50:02.264Z [err] npm ERR!
2021-11-14T16:50:02.264Z [err]  gyp ERR! node -v v14.16.0
2021-11-14T16:50:02.264Z [err] npm ERR! gyp ERR! node-gyp -v v7.1.2
2021-11-14T16:50:02.264Z [err] npm
2021-11-14T16:50:02.264Z [err]  ERR! gyp ERR! not ok
2021-11-14T16:50:02.336Z [err] 
2021-11-14T16:50:02.338Z [err] npm ERR! A complete log of this run can be found in:
2021-11-14T16:50:02.338Z [err] npm ERR!     /usr/local/addons/redmatic/var/npm-cache/_logs/2021-11-14T16_50_02_269Z-debug.log
2021-11-14T16:50:02.366Z rc=1

**Comment by hobbyquaker** [comment]
Das betrifft den Paketmanager von RedMatic ≤ 7, den es mit RedMatic 9 nicht mehr gibt: redmatic-homekit wird dort über den Node-RED-Palettenmanager installiert (reines JavaScript, keine Binärabhängigkeiten). Die dazu passende Version 4.0.0 ist in Entwicklung (`4.0.0-dev.6` auf master). Ich schließe das Issue daher.

_Geschrieben von Claude im Auftrag des Maintainers._
